import React from "react";
import Head from "next/head";
import Link from "next/link";
import { routeConfig } from "@/config";

const Categories = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Meta {...metaData} /> */}
      Каталог
      <Link href={routeConfig.ABOUT_URL} passHref>
        About
      </Link>
    </>
  );
};

export default Categories;
